language: cpp
compiler:
    - g++

install:
    # get c++11 support
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

before_script:
    # setup environment
    - wget https://raw.githubusercontent.com/cmu-db/peloton/master/scripts/vagrant/packages.sh
    - sudo sh ./packages.sh

script:
    # bootstrap
    - ./bootstrap
    - cd build
    - ../configure
    # make
    - make -j3
    # run tests
    - make check
